( function( QUnit ) {

	/* jshint -W054 */
	/* jshint -W060 */

	"use strict";

	var config = getJS( "../build/config.json" );
	config.date = new Date();
	config.year = config.date.getFullYear();

	document.write( "<title>" + config.name + " test suite</title>" );

	// UTILITIES

	function loadScript( url ) {
		document.write( "<script src='" + url + "'></script>\n" );
	}

	function getJS( url ) {
		var xhr = new XMLHttpRequest();
		xhr.open( "GET", url, false );
		xhr.send();
		return new Function( "return " + xhr.responseText + ";" )();
	}

	function build() {
		return getJS( "../build/io/includeFile.js" )( config )( "../build/dist/" + config.name +".js").content;
	}

	// ADD URL OPTIONS

	QUnit.config.urlConfig.push( {
		id: "dist",
		label: "Load built file",
		tooltip: "Load 'use.js' as generated by the build process"
	}, {
		id: "min",
		label: "Load minified file",
		tooltip: "Load 'use.min.js' as generated by the build process"
	} );

	// LOAD USEJS

	if ( QUnit.urlParams.min ) {

		loadScript( "../dist/use.min.js" );

	} else if ( QUnit.urlParams.dist ) {

		loadScript( "../dist/use.js" );

	} else {

		document.write( "<script>//<!--\n" + build() + "\n//--></script>" );

	}

	// LOAD INIT

	loadScript( "init.js" );

	// LOAD UNIT TESTS

	for ( var unit in getJS( "units.json" ) ) {
		loadScript( "unit/" + unit + ".js" );
	}

} )( window.QUnit );
